### PR TITLE
fix: Invariant violation err fixed. Sometimes the part object has the…

### PR DESCRIPTION
**Pull request by SheriefBadran**
… key text but the value is an empty string, in those cases part.text was accidently validated to false.

### CODE REVIEW

**Comment by MoombaDS** [comment]
Hmm, I can see the reasoning behind this fix, but I'm not completely convinced by the handling.

Surely if we somehow end up with a part that contains a text key but an empty string as a value then something has either gone horribly wrong or whoever added the line screwed up pretty badly - it seems to me that this would be a situation we completely want to avoid rather than just printing a blank message and confusing the player. If it did somehow happen, perhaps it would make sense to throw an error or something along those lines so that the mistake would immediately be caught during the run of the test suite rather than making it into production?

**Comment by SheriefBadran** [comment]
well I agree with you, and also I'm a little uncertain about part sometimes being an object and sometimes a string? It is just that as it was, the game broke because of the invariant violation error. Do you want me to improve the solution prior to merge?

**Comment by MoombaDS** [comment]
The idea of part sometimes being an object and sometimes being a string was to cut down on a lot of unnecessary stuff within the messages - the only possible reason for a part to be an object is if it has a `className` assigned to it to provide formatting, otherwise it may as well just be a plain string. Originally it was always an object but in the cases where there would be no formatting, it would be an object with only a single key-value pair (always a string) which was just adding a lot of unnecessary padding when it could easily be a plain string instead.

It would be awesome if you could improve the solution before I merge!

**Comment by SheriefBadran** [comment]
ok, I'll give it a shot :)

**Comment by SheriefBadran** [comment]
Hey! Im sorry to say this, there is a bad mistake on my part here. When I was going to dive into the job improving the bug fix I first wanted to check where the empty string actually came from. To my disappointment I found out those empty strings were left in the old state since my last PR, when I was in the middle of the refactoring things not working properly yet. Sorry for bothering you with this PR, I should have traced the empty strings from start saving us both some time... I might bother you with a new better PR soon if you don't mind :)

**Comment by MoombaDS** [comment]
No worries! It happens!

I always look forward to any PRs I might get! :smile:

**Comment by krawaller** [comment]
A really good discussion in this PR, guys! Well done the both of you! :)

**Pull request closed without merging**
